/**
 * Metal Hub — Permission Codes & Client-Side Permission Matrix
 *
 * This is a STATIC mirror of the permissions seeded in the database.
 * Used for client-side UI gating (show/hide buttons, menu items).
 * The server enforces permissions authoritatively via the DB.
 */

// ── Permission code constants ──
export const PERMISSIONS = {
  // Users
  USERS_LIST: 'users.list',
  USERS_READ: 'users.read',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',
  USERS_BAN: 'users.ban',
  USERS_ROLES_ASSIGN: 'users.roles.assign',

  // Listings
  LISTINGS_CREATE: 'listings.create',
  LISTINGS_READ: 'listings.read',
  LISTINGS_UPDATE: 'listings.update',
  LISTINGS_DELETE: 'listings.delete',
  LISTINGS_MODERATE: 'listings.moderate',
  LISTINGS_FEATURE: 'listings.feature',

  // Admin
  ADMIN_DASHBOARD: 'admin.dashboard',
  ADMIN_SETTINGS: 'admin.settings',
  ADMIN_ROLES: 'admin.roles',
  ADMIN_AUDIT: 'admin.audit',
  ADMIN_ANALYTICS: 'admin.analytics',
  ADMIN_BANNERS: 'admin.banners',
  ADMIN_CAPABILITIES: 'admin.capabilities',

  // CRM
  CRM_LEADS_LIST: 'crm.leads.list',
  CRM_LEADS_CREATE: 'crm.leads.create',
  CRM_LEADS_UPDATE: 'crm.leads.update',
  CRM_LEADS_DELETE: 'crm.leads.delete',
  CRM_PIPELINE: 'crm.pipeline',
  CRM_ANALYTICS: 'crm.analytics',

  // Storage
  STORAGE_UPLOAD: 'storage.upload',
  STORAGE_DELETE: 'storage.delete',
  STORAGE_MODERATE: 'storage.moderate',
  STORAGE_ADMIN: 'storage.admin',

  // Settings
  SETTINGS_OWN_READ: 'settings.own.read',
  SETTINGS_OWN_UPDATE: 'settings.own.update',
  SETTINGS_PLATFORM_READ: 'settings.platform.read',
  SETTINGS_PLATFORM_UPDATE: 'settings.platform.update',

  // Notifications
  NOTIFICATIONS_READ: 'notifications.read',
  NOTIFICATIONS_MANAGE: 'notifications.manage',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/**
 * Client-side permission matrix.
 * Maps role → array of permission codes.
 * 
 * This is a STATIC copy for UI rendering speed.
 * The database `role_permissions` table is the authoritative source.
 * Always keep this in sync with migration seeds.
 */
export const CLIENT_PERMISSION_MATRIX: Record<string, readonly string[]> = {
  super_admin: Object.values(PERMISSIONS),

  admin: Object.values(PERMISSIONS).filter(
    (p) => p !== PERMISSIONS.ADMIN_ROLES && p !== PERMISSIONS.SETTINGS_PLATFORM_UPDATE && p !== PERMISSIONS.USERS_DELETE,
  ),

  moderator: [
    PERMISSIONS.USERS_LIST, PERMISSIONS.USERS_READ, PERMISSIONS.USERS_BAN,
    PERMISSIONS.LISTINGS_READ, PERMISSIONS.LISTINGS_MODERATE,
    PERMISSIONS.ADMIN_DASHBOARD, PERMISSIONS.ADMIN_ANALYTICS,
    PERMISSIONS.STORAGE_MODERATE,
    PERMISSIONS.CRM_LEADS_LIST, PERMISSIONS.CRM_LEADS_CREATE, PERMISSIONS.CRM_LEADS_UPDATE,
    PERMISSIONS.SETTINGS_OWN_READ, PERMISSIONS.SETTINGS_OWN_UPDATE,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],

  support_agent: [
    PERMISSIONS.USERS_LIST, PERMISSIONS.USERS_READ,
    PERMISSIONS.LISTINGS_READ,
    PERMISSIONS.ADMIN_DASHBOARD,
    PERMISSIONS.CRM_LEADS_LIST, PERMISSIONS.CRM_LEADS_CREATE, PERMISSIONS.CRM_LEADS_UPDATE,
    PERMISSIONS.SETTINGS_OWN_READ, PERMISSIONS.SETTINGS_OWN_UPDATE,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],

  supplier_success: [
    PERMISSIONS.USERS_LIST, PERMISSIONS.USERS_READ,
    PERMISSIONS.LISTINGS_READ, PERMISSIONS.LISTINGS_MODERATE,
    PERMISSIONS.ADMIN_DASHBOARD, PERMISSIONS.ADMIN_ANALYTICS,
    PERMISSIONS.CRM_LEADS_LIST, PERMISSIONS.CRM_LEADS_CREATE, PERMISSIONS.CRM_LEADS_UPDATE,
    PERMISSIONS.CRM_PIPELINE, PERMISSIONS.CRM_ANALYTICS,
    PERMISSIONS.SETTINGS_OWN_READ, PERMISSIONS.SETTINGS_OWN_UPDATE,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],

  finance: [
    PERMISSIONS.ADMIN_DASHBOARD, PERMISSIONS.ADMIN_ANALYTICS,
    PERMISSIONS.SETTINGS_OWN_READ, PERMISSIONS.SETTINGS_OWN_UPDATE,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],

  marketing: [
    PERMISSIONS.ADMIN_DASHBOARD, PERMISSIONS.ADMIN_BANNERS, PERMISSIONS.ADMIN_CAPABILITIES,
    PERMISSIONS.LISTINGS_READ, PERMISSIONS.LISTINGS_FEATURE,
    PERMISSIONS.SETTINGS_OWN_READ, PERMISSIONS.SETTINGS_OWN_UPDATE,
    PERMISSIONS.NOTIFICATIONS_READ, PERMISSIONS.NOTIFICATIONS_MANAGE,
  ],

  seller: [
    PERMISSIONS.LISTINGS_CREATE, PERMISSIONS.LISTINGS_READ, PERMISSIONS.LISTINGS_UPDATE, PERMISSIONS.LISTINGS_DELETE,
    PERMISSIONS.STORAGE_UPLOAD, PERMISSIONS.STORAGE_DELETE,
    PERMISSIONS.SETTINGS_OWN_READ, PERMISSIONS.SETTINGS_OWN_UPDATE,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],

  manufacturer: [
    PERMISSIONS.LISTINGS_CREATE, PERMISSIONS.LISTINGS_READ, PERMISSIONS.LISTINGS_UPDATE, PERMISSIONS.LISTINGS_DELETE,
    PERMISSIONS.STORAGE_UPLOAD, PERMISSIONS.STORAGE_DELETE,
    PERMISSIONS.SETTINGS_OWN_READ, PERMISSIONS.SETTINGS_OWN_UPDATE,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],

  buyer: [
    PERMISSIONS.LISTINGS_READ,
    PERMISSIONS.STORAGE_UPLOAD, PERMISSIONS.STORAGE_DELETE,
    PERMISSIONS.SETTINGS_OWN_READ, PERMISSIONS.SETTINGS_OWN_UPDATE,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],

  both: [
    PERMISSIONS.LISTINGS_CREATE, PERMISSIONS.LISTINGS_READ, PERMISSIONS.LISTINGS_UPDATE, PERMISSIONS.LISTINGS_DELETE,
    PERMISSIONS.STORAGE_UPLOAD, PERMISSIONS.STORAGE_DELETE,
    PERMISSIONS.SETTINGS_OWN_READ, PERMISSIONS.SETTINGS_OWN_UPDATE,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],

  distributor: [
    PERMISSIONS.LISTINGS_CREATE, PERMISSIONS.LISTINGS_READ, PERMISSIONS.LISTINGS_UPDATE, PERMISSIONS.LISTINGS_DELETE,
    PERMISSIONS.STORAGE_UPLOAD, PERMISSIONS.STORAGE_DELETE,
    PERMISSIONS.SETTINGS_OWN_READ, PERMISSIONS.SETTINGS_OWN_UPDATE,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],

  logistics: [
    PERMISSIONS.LISTINGS_READ,
    PERMISSIONS.SETTINGS_OWN_READ, PERMISSIONS.SETTINGS_OWN_UPDATE,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],
};

/**
 * Check if a role has a specific permission (client-side).
 * For UI gating only — server enforces authoritatively.
 */
export function hasClientPermission(role: string | null | undefined, permission: string): boolean {
  if (!role) return false;
  const perms = CLIENT_PERMISSION_MATRIX[role];
  if (!perms) return false;
  return perms.includes(permission);
}
